server:
    port: 8080

spring:
  application:
      name: customer
  datasource:
    username: 'vivek'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'vivek1234'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
